config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "(*any)", to: redirect(ENV.fetch("OFFERKARMA_BASE_URL")),
                constraints: ->(request) { request.subdomain == "www" }

  get "(*any)", to: redirect(ENV.fetch("OFFERKARMA_BASE_URL")),
                constraints: ->(request) { request.domain == ENV.fetch("SECOND_DOMAIN") }

  ActiveAdmin.routes(self)

  root to: "pages#index"

  get "equity",    to: "pages#equity"
  get "negotiate", to: "pages#negotiate"

  get "terms-of-service", to: "pages#terms"
  get "privacy-policy",   to: "pages#privacy"

  get    "login",                    to: "users#login"
  post   "login",                    to: "users#post_login"
  get    "signup",                   to: "users#signup"
  post   "signup",                   to: "users#create"
  delete "logout",                   to: "users#logout"
  get    "account",                  to: "users#account"
  get    "verify/:token",            to: "users#verify", as: :verify

  get    "unsubscribe",              to: "emails#show"
  patch  "unsubscribe",              to: "emails#update"

  get    "enterprise",               to: "pages#enterprise"

  resources :companies, only: [:show]
  resources :offers do
    member do
      post :votes
      post :comments
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  belongs_to :company, optional: true
  has_many :referrals

  attr_accessor :verification_token

  validates :password, length: { minimum: 6 }, if: :setting_password?
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  has_many :offers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  before_save { email.downcase! }
  before_create :create_verification_digest

  # TODO: move to a lib
  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end

    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  end

  def username
     read_attribute(:username) || uuid.first(8)
  end

  def upvoted?(offer)
    offer.upvotes.where(user: self).exists?
  end

  def downvoted?(offer)
    offer.downvotes.where(user: self).exists?
  end

  def uses_corporate_email?
    !!find_company
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def verified?
    !!verified_at
  end

  def verify!
    self.company = find_company
    self.verification_digest = nil
    self.verified_at = DateTime.now
    save!
  end

  private

  def setting_password?
    password || password_confirmation
  end

  def find_company
    Company.find_or_create_from_clearbit!(email_domain)
  end

  def email_domain
    email.split("@").last
  end

  def create_verification_digest
    self.verification_token = User.new_token
    self.verification_digest = User.digest(self.verification_token)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :store_return_to, except: %i[account]
  before_action :redirect_to_login_if_needed, only: %i[account]
  before_action :redirect_to_offers_if_logged_in, only: %i[login post_login signup create]

  def account
    @offers = Offer.filter(user: current_user)
  end

  def login; end

  def post_login
    user = User.find_by(email: user_params[:email].downcase)
    verify_recaptcha!(model: user, env: Rails.env)
    if user&.authenticate(user_params[:password])
      log_in user
      redirect_back
    else
      flash.now[:danger] = "Invalid email/password combination"
      render :login
    end
  end

  def signup
    @user = User.new
  end

  def create
    user_attr = user_params
    user_attr[:password_confirmation] = user_attr[:password]
    @user = User.new(user_attr)
    verify_recaptcha!(model: @user, env: Rails.env)
    Services.user_registration.sign_up(user: @user)
    log_in @user
    redirect_back
  rescue Users::Registration::UserCreationError
    flash.now[:danger] = "Invalid email/password combination"
    render :signup
  end

  def logout
    log_out
    redirect_to root_path
  end

  def verify
    @user = User.find_by_email(params[:email])
    if @user &&
      !@user.verified? &&
      @user.authenticated?(:verification, params[:token])
      @user.verify!
      log_in @user
    else
      render 'verify_failed'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def email_param
    params.require(:user).permit(:email, :password)
  end
end

app/views/users/account.html.erb
<div class="text-center homepage-header p-4 bg-dark text-white">
  <div class="lead">Account</div>
  <div class="small font-weight-light">Manage your offers</div>
  <% if @offers.any? %>
    <div class="text-center mt-3">
      <a class="btn btn-danger" href="<%= new_offer_path %>">Add a new offer</a>
    </div>
  <% end %>
</div>

<div class="bg-light p-3 border-bottom">
  <div class="container p-2">
    <% if current_user.offers.none? %>
      <div class="bg-white p-3 text-center">
        <div class="lead mb-2">
          You haven't submitted any offers yet.
        </div>
        <a class="btn btn-danger" href="<%= new_offer_path %>">Submit your first offer now</a>
      </div>
    <% end %>
    <div class="row">
      <% @offers.each do |offer| %>
        <%= render partial: "offers/offer_list_item", locals: { offer: offer } %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/login.html.erb
<div class="text-center homepage-header p-4 bg-dark">
  <div class="text-white">
    <div class="lead">
      Welcome back
    </div>

    <div class="small font-weight-light">
      Login to manage your offers and get or provide feedback.
    </div>
  </div>
</div>

<div class="bg-light p-4">
  <div class="container bg-white center-box-max-width card-shadow p-4 rounded">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= form_for :user, url: login_path do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control", placeholder: "bob@apple.com", required: "true" %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", required: "true", pattern: ".{6,}" %>
         <small>
          <a href="/login">Forgot password</a>
        </small>
      </div>

      <%= invisible_recaptcha_tags text: "Login", class: "btn btn-block btn-success" %>
    <% end %>

    <div class="mt-2 text-center">
      <div>
        <a href="/signup">Or create an account</a>
      </div>
    </div>
  </div>
</div>

app/views/users/signup.html.erb
<div class="text-center homepage-header p-4 bg-dark">
  <div class="text-white">
    <div class="lead">
      Unleash feedback
    </div>

    <div class="small font-weight-light">
      Creating an account will allow you to post offers and provide feedback.
    </div>
  </div>
</div>

<div class="bg-light p-4">
  <div class="container bg-white center-box-max-width card-shadow p-4 rounded">
    <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <ul class="list-unstyled">
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for(@user, url: signup_path) do |f| %>
      <div class="form-group">
        <%= f.label :email, value: "Work email" %>
        <%= f.email_field :email, class: "form-control", placeholder: "bob@apple.com", required: "true" %>
        <small class="form-text text-muted">Using your work email will allow you to make referrals and see offers that are only visible for your company.</small>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", required: "true",  pattern: ".{6,}" %>
      </div>
      <%= invisible_recaptcha_tags text: "Create my account", class: "btn btn-block btn-success" %>
    <% end %>
    <div class="mt-2 text-center">
      <div>
        <a href="/login">I already have an account</a>
      </div>
    </div>
  </div>
</div>

app/views/users/verify.html.erb
<div class="text-center homepage-header p-4 bg-dark">
  <div class="text-white">
    <div class="lead">
      You are now verified <span class="fa fa-check"></span>
    </div>
  </div>
</div>

<div class="bg-light p-4">
  <div class="container bg-white center-box-max-width p-4 rounded">
    <div class="text-center">
      <div class="mb-3">
        <% if current_user.company %>
          <div class="lead mb-3">You are all set!</div>

          <div class="mb-3">
            We were able to verify that you are currently working for:
          </div>

          <div>
            <img width="80px" class="rounded" src="<%= current_user.company.logo_url %>">
          </div>

          <div class="mb-3">
            <a href="<%= company_path current_user.company.uuid %>" class="btn btn-link text-danger">
              See offers from <%= current_user.company.name %>
            </a>
          </div>
        <% else %>
          <div class="font-weight-bold mb-3">
            Unfortunately, we did not detect any company from the email address you used to register with.
          </div>

          <div>
            Don't worry you can still use OfferKarma. The only downside is that you won't be able to see some offers restricted to some companies.

            If you wish to be verified with a company, please sign up again using your work email this time.
          </div>
        <% end %>
      </div>

      <div>
        <% if current_user.offers&.none? %>
          <a href="<%= new_offer_path %>" class="btn btn-danger">Evaluate my first offer</a>
        <% else %>
          <a href="<%= account_path %>" class="btn btn-outline-danger">Manage my offers</a>
        <% end %>
        or <a href="<%= offers_path %>" class="btn btn-outline-danger">See our most recent offers</a>
      </div>
    </div>
  </div>
</div>

app/views/users/verify_failed.html.erb
<div class="text-center homepage-header p-4 bg-dark">
  <div class="text-white">
    <div class="lead">
      Verification failed <span class="fa fa-exclamation-triangle"></span>
    </div>
  </div>
</div>

<div class="bg-light p-4">
  <div class="container bg-white p-4 rounded text-center">
    <div class="lead mb-3">
      <% if current_user&.verified? %>
        Your account has already been verified!
      <% else %>
        Sorry, this verification link has expired or is invalid.
      <% end %>
    </div>
    <a href="<%= root_url %>" class="btn btn-danger">Go back home</a>
  </div>
</div>