config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "(*any)", to: redirect(ENV.fetch("OFFERKARMA_BASE_URL")),
                constraints: ->(request) { request.subdomain == "www" }

  get "(*any)", to: redirect(ENV.fetch("OFFERKARMA_BASE_URL")),
                constraints: ->(request) { request.domain == ENV.fetch("SECOND_DOMAIN") }

  ActiveAdmin.routes(self)

  root to: "pages#index"

  get "equity",    to: "pages#equity"
  get "negotiate", to: "pages#negotiate"

  get "terms-of-service", to: "pages#terms"
  get "privacy-policy",   to: "pages#privacy"

  get    "login",                    to: "users#login"
  post   "login",                    to: "users#post_login"
  get    "signup",                   to: "users#signup"
  post   "signup",                   to: "users#create"
  delete "logout",                   to: "users#logout"
  get    "account",                  to: "users#account"
  get    "verify/:token",            to: "users#verify", as: :verify

  get    "unsubscribe",              to: "emails#show"
  patch  "unsubscribe",              to: "emails#update"

  get    "enterprise",               to: "pages#enterprise"

  resources :companies, only: [:show]
  resources :offers do
    member do
      post :votes
      post :comments
    end
  end
end

app/views/layouts/_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-134218353-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-134218353-1');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render "layouts/analytics" if Rails.env.production? %>

    <title>
      <% if @offer&.created_at %>
        <%= @offer.og_title %>
      <% elsif @offer %>
        OfferKarma - Evaluate your job offer
      <% elsif @referral&.created_at %>
        <%= @referral.og_title %>
      <% elsif @referral %>
        OfferKarma - Request a referral
      <% elsif @company %>
        OfferKarma - <%= @company.display_name %>
      <% else %>
        OfferKarma - Job offer evaluation and feedback community
      <% end %>
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.png') %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//platform-api.sharethis.com/js/sharethis.js#property=5c7578d85011cb0011347628&product=inline-share-buttons" async="async"></script>

    <meta property="og:type" content="article" />
    <meta property="fb:app_id" content="" />

    <% if @offer&.created_at %>
      <meta property="og:title" content="<%= @offer.og_title %>" />
      <meta property="og:description" content="<%= @offer.og_description %>" />
      <meta property="og:image" content="<%= @offer.company.logo_url %>" />
      <meta property="og:url" content="<%= offer_url @offer.uuid %>" />
    <% elsif @referral&.created_at %>
      <meta property="og:title" content="<%= @referral.og_title %>" />
      <meta property="og:description" content="<%= @referral.og_description %>" />
      <meta property="og:image" content="<%= @referral.company.logo_url %>" />
      <meta property="og:url" content="<%= referral_url @referral.uuid %>" />
    <% else %>
      <meta property="og:url" content="https://offerkarma.com" />
      <meta property="og:title" content="OfferKarma - Job offer feedback community" />
      <meta property="og:description" content="We empower candidates by providing anonymous feedback on any job offer." />
      <meta property="og:image" content="<%= asset_url('og-image.png') %>" />
    <% end %>
  </head>

  <body>
    <header class="border-bottom">
      <div class="container">
        <nav class="pl-0 pr-0 navbar navbar-light <%= logged_in? ? 'navbar-expand-sm' : 'navbar-expand' %>  my-2 my-lg-0 bg-white">
          <a class="navbar-brand" href="/">Offer<span class="text-success font-weight-bold">Karma</span></a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item mr-sm-3 mb-sm-0 mb-2">
                <a class="nav-link btn btn-sm btn-outline-light text-dark font-weight-bold" href="/offers">View latest offers</a>
              </li>
              <% if logged_in? %>
                <li class="nav-item">
                  <%= link_to logout_path, method: :delete, data: { confirm: "Are you sure you want to log out?" }, class: "nav-link btn btn-sm btn-link text-danger" do %>
                      Log out  <small>(<%= current_user.email %>)</small>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <a class="nav-link btn btn-sm btn-link text-success" href="/login">Sign-in</a>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </header>

    <%= yield %>

    <div class="p-3 text-center bg-light border-bottom">
      <a href="https://www.producthunt.com/posts/reffo?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-reffo" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=150711&theme=dark" alt="OfferKarma - Receive feedback on job offers | Product Hunt Embed" style="width: 250px; height: 54px;" width="250px" height="54px" /></a>
    </div>

    <footer class="p-3 pb-5 mb-5 text-center">
      <div class="mb-3 font-weight-bold">
        <div class="h5 mb-2">
          &copy; OfferKarma
        </div>
      </div>
      <div class="mb-2">
        <a href="mailto:hello@offerkarma.com?subject=Feedback" target="_blank" class="btn btn-sm btn-outline-primary"><span class="far fa-paper-plane"></span> Email us your suggestions</a>
      </div>
      <div class="mb-2 small text-muted">
        Made with <span class="text-success fa fa-heart"></span> in San Francisco
      </div>
      <div class="small">
        <%= link_to "Terms of Service", terms_of_service_path, class: "text-dark" %> -
        <%= link_to "Privacy Policy", privacy_policy_path, class: "text-dark" %>
      </div>
      <div class="text-ghost">
        Company logos provided by <a href="https://clearbit.com" target="_blank" class="text-ghost">Clearbit</a>
      </div>
    </footer>
  </body>
</html>